### ISSUE TITLE
Comma Sepearated Values Compass Exports

### ISSUE THREAD

**Issue by ox-baloo** [the-scouts/compliance-dashboard#3]
![image](https://user-images.githubusercontent.com/41539451/80310043-8c005200-87d0-11ea-9d21-07e2c1fbfb92.png)

The Compliance Dashboard Assistant v4 does not pick up '.csv' files in the open 'Excel file' dialog box. Is it normal for exports to be .csv or .xlsx?

**Comment by AA-Turner** [comment]
Input is the output from the compliance and training assistants.

I'll send you the links
